apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "django-app.fullname" . }}
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  replicas: {{ ternary .Values.autoscaling.minReplicas 1 .Values.autoscaling.enabled }}
  selector:
    matchLabels:
      {{- include "django-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "django-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: django
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ default 8000 .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "django-app.fullname" . }}
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ default 8000 .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ default 8000 .Values.service.targetPort }}
            initialDelaySeconds: 30
            periodSeconds: 20
