apiVersion: v1
kind: Secret
metadata:
  name: apps-repo
  namespace: {{ .Release.Namespace }}
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  url: {{ .Values.appsRepoUrl | quote }}

